### ISSUE TITLE
Deluge Python modules

### ISSUE THREAD

**Issue by JoeStratton** [cpoppema/docker-flexget#10]
How hard/bloaty would it be to add the deluge python package to this? It does not need to be running, but in order for flexget to communicate with a separate deluge container it must have the local code accessible. I dont see it as a resource issue since it doesnt need to run, but it would increase the image size.

edit: package needed "deluge-common"

**Comment by cpoppema** [comment]
I will take a look to set it up myself and make sure everything works, but that is going to have to wait a few days. The system package that is available is https://packages.ubuntu.com/en/xenial/deluge-common, it seems like that is the one ? (a few minor releases behind the latest)

I'll also consider the increased image size and maybe there is a way to get around it. E.g. an environment flag could be used to toggle between installing/updating transmission _or_ deluge. The first install then happens on the first run (nothing would be pre-installed), not costing any extra bytes in the image, but it would take a little longer to start the first time. If there are no python packages that are used by both torrent clients (zero change of any conflicts) I will simply be having them both pre-installed.

**Comment by JoeStratton** [comment]
I am unsure what transmission requires as I do not use it, but yes that is the correct deluge package. It is the core python files, but not the GUI. Which is exactly what flexget requires to communicate with a deluge instance outside of the container.

Good to hear it doesnt seem to hard, thanks for adding it to your "todo's"!

**Comment by cpoppema** [comment]
For now I have added a flag. If you create a container anew with `-e TORRENT_PLUGIN=deluge` it should install "deluge-common" and check for updates on restart. If you leave out `TORRENT_PLUGIN` it will still install and update "transmissionrpc".

**Comment by JoeStratton** [comment]
Thanks, will test and report back.

edit: working great, thanks!
