### ISSUE TITLE
FLEXGET_LOG_LEVEL is not adhered to

### ISSUE THREAD

**Issue by adamwinn** [cpoppema/docker-flexget#14]
I set FLEXGET_LOG_LEVEL to `info` but flexget is still running in debug mode

```
root@cpoppema-docker-flexget-copy:/# ps -ef | grep flexget
root        35    33  0 18:47 ?        00:00:00 runsv flexget
abc         39    35  0 18:47 ?        00:00:16 /usr/bin/python /usr/local/bin/flexget -c /config/config.yml --loglevel debug daemon start --autoreload-config
root        74    57  0 19:38 ?        00:00:00 grep --color=auto flexget
root@cpoppema-docker-flexget-copy:/# echo $FLEXGET_LOG_LEVEL
info
```

**Comment by cpoppema** [comment]
Thanks for reporting this @adamwinn. Can you please show me how you set FLEXGET_LOG_LEVEL to info so I can retrace those steps myself ?

**Comment by adamwinn** [comment]
I'm on a Synology NAS.  I do it thru their Docker application

![image](https://user-images.githubusercontent.com/3028964/30151241-e1b44f3c-936b-11e7-8723-2023b85ef7ff.png)

**Comment by cpoppema** [comment]
So far it looks fine when creating and starting a docker container with different log levels using a terminal. I'm going to try to get my hands on a Synology myself to fiddle around with it to see if I can recreate this issue.

**Comment by cpoppema** [comment]
Unfortunately, the device I could test with was a DS214play. This model is not supported by the docker package (see https://www.synology.com/en-us/dsm/packages/Docker), so I'm afraid I can't try to reproduce and fix this issue.

**Comment by bagobones** [comment]
I am using a synology DS916+ the variable appears to correctly set the log level on my unit.. I tested with verbose and info.

Have you tried backing up the container config, downloading the latest image then importing the container config again to bring it to the latest version?

**Comment by mastermindg** [comment]
Setting FLEXGET_LOG_LEVEL works fine outside of Synology. I've experienced a lot of weirdness with Synology packages over the years. I wouldn't be surprised if this is a bug with their implementation of Docker. I would recommend opening up a support ticket with Synology.

**Comment by Noki** [comment]
I have this running on a Synology NAS and setting this works for me (DSM 6.1.4-15217 Update 2 with Docker Package 17.05.0-349).

![image](https://user-images.githubusercontent.com/198902/33682117-ca6c890a-dac6-11e7-93f7-dc5e18f3c6f9.png)

@mastermindg do you still have the problem?

**Comment by cpoppema** [comment]
Since others are reporting it to work on their synology just fine, I have to believe it's not an issue with the container. You can always create a new issue if it still doesn't work.
