### ISSUE TITLE
Daemon mode

### ISSUE THREAD

**Issue by konsumer** [cpoppema/docker-flexget#3]
I love this docker container, especially in the linuxserver ecosystem but I wish it worked with [daemon mode](https://flexget.com/Daemon) instead of cron, so I can run the web-ui.

**Comment by konsumer** [comment]
`flexget daemon start -d --config-autoreload` would be best for my purposes, I think.

**Comment by cpoppema** [comment]
Hi @konsumer, thanks for your suggestion!

I'm trying it out right now, because it sounds good: running it daemonized won't alter the existing behavior of running the tasks every hour and then you can run a web-ui if you want to :)

I've had to dig a little in the flexget source because the wiki was outdated for versions >2.6.0: `--config-autoreload` is now `--autoreload-config`.

**Comment by konsumer** [comment]
Ah! cool. I tried running it with `docker exec` for daemon-mode but got a port conflict (I think yours was also running on 5050 with my web-enabled config file.) I might just make a new docker container fork of yours and starts the daemon only, because I like the idea of not needing cron and running the web interface, by default. The [internal scheduler](https://flexget.com/Plugins/Daemon/scheduler) seems fine for cron-like stuff, and the webui is super-handy and lets me edit the config file remotely (it's nice to not have to ssh in to do stuff) as well as see everything that's going on. It feels like sonarr-light, but with way more configuration options. 

I had another idea, possibly unrelated, but I imagine something like this in ~abc/.flexget/config.yml:

```yml
# sensible defaults here
include: /config/config.yml
```

This way the file-layout is the same (using /config volume) and some basic defaults can be setup.

**Comment by cpoppema** [comment]
I've just pushed a branch with a working daemon-mode as far as I can tell. Are you able to test it and see if it fits your needs ?

**Comment by konsumer** [comment]
I can test tonight when I get home. Thanks!

**Comment by konsumer** [comment]
Actually, I couldn't wait to test, but unsure how how to build it from the branch. I'm new to docker, so I'm sure I'm doing something dumb.

I tried:
```
$ docker build  -e PGID=1000 -e PUID=1000 -v ./config:/config -v ./downloads:/downloads docker-flexget-feature-run-daemonized-for-web-ui
unknown shorthand flag: 'e' in -e
See 'docker build --help'.
```

and

```
$ docker create --name=flexget -e PGID=1000 -e PUID=1000 -v ./config:/config -v ./downloads:/downloads docker-flexget-feature-run-daemonized-for-web-ui/
Error parsing reference: "docker-flexget-feature-run-daemonized-for-web-ui/" is not a valid repository/tag
```

**Comment by cpoppema** [comment]
Almost there. You don't need to pass all the arguments when building.

```
git checkout feature/run-daemonized-for-web-ui
docker build -t docker-flexget-feature-run-daemonized-for-web-ui .
docker run --rm \
    --name=flexget \
    -e PGID=1000 -e PUID=1000 \
    -p 5050:5050 \
    -v ./config:/config \
    -v ./downloads:/downloads \
    docker-flexget-feature-run-daemonized-for-web-ui
```

Things to look out for when building local:
`docker build -t <image-name> .` will make this image available with `image-name` when creating or running a container

`docker build` can be re-run as often as you want with the same tag, it will overwrite it with the latest image if the build finishes.

If you use `docker create`, you'd also need to run `docker start flexget`, `docker stop flexget`, `docker rm flexget` before running `docker create` a second time. In contrast, `docker run --rm` wil automatically remove the container once stopped.

**Comment by konsumer** [comment]
I'm getting lots of errors like this:

```
2017-01-11 07:16 DEBUG    manager                       Config file /config/config.yml selected
2017-01-11 07:16 DEBUG    manager                       sys.defaultencoding: ascii
2017-01-11 07:16 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2017-01-11 07:16 DEBUG    manager                       flexget detected io encoding: utf-8
2017-01-11 07:16 DEBUG    manager                       os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2017-01-11 07:16 DEBUG    manager                       Sending command to running FlexGet process: [u'-c', u'/config/config.yml', u'--loglevel', u'debug', u'daemon', u'start', u'--autoreload-config']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 305, in start
    client = IPCClient(ipc_info['port'], ipc_info['password'])
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 158, in __init__
    channel = rpyc.Channel(rpyc.SocketStream.connect('127.0.0.1', port))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 132, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 102, in _connect
    s.connect(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```

I am running it like this:

```
docker run --rm     --name=flexget     -e PGID=1000 -e PUID=1000     -p 5050:5050     -v /mnt/media/server/flexget:/config     -v /mnt/media/:/media     docker-flexget-feature-run-daemonized-for-web-ui
```

/mnt/media/ is recursively owned by 1000:1000

**Comment by cpoppema** [comment]
Hmm. The baseimage will make sure the file `services/flexget/run` is always up and running. That means that you need to start a "blocking" program from this file. This is exactly what `flexget daemon start` does: only with the optional `-d` it moves to the background, exiting the file and triggers the baseimage to start it _again_ which results to similar log messages:

```
2017-01-11 17:44 ERROR    manager   Daemon already running for this config.
2017-01-11 17:44 DEBUG    manager   Config file /config/config.yml selected
2017-01-11 17:44 DEBUG    manager   sys.defaultencoding: ascii
2017-01-11 17:44 DEBUG    manager   sys.getfilesystemencoding: UTF-8
2017-01-11 17:44 DEBUG    manager   flexget detected io encoding: utf-8
2017-01-11 17:44 DEBUG    manager   os.path.supports_unicode_filenames: False
There is a FlexGet process already running for this config, sending execution there.
2017-01-11 17:44 DEBUG    manager   Sending command to running FlexGet process: [u'-c',
    u'/config/config.yml', u'--loglevel', u'debug', u'daemon', u'start', u'-d',
    u'--autoreload-config']
2017-01-11 17:44 ERROR    manager   Daemon already running for this config
```
.. over and over. The error "connection refused" refers to the connection that flexget attempts to make with a previously started flexget. It _might_ mean that the first `daemon start` never started properly and is still exiting when the new one already tries to defer the command to the already-running flexget but it never gets there.

Can you post the output from the start up to the first mention that "There is a FlexGet process already running for this config, sending execution there." ? Can you also retry with a cleaner configuration (don't forget to set aside your "live" config folder) ? For example: 

```
web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 1

tasks:
  test task:
    rss: http://mysite.com/myfeed.rss
    series:
      - My Favorite Show
```

I let it run for a few times as you can see here: http://pastebin.com/raw/BkLpWneW

If this _does_ work for you, try moving over/replacing configuration per plugin from your original yml to this new yml until it stops working, if that happens then we have something to look into.

**Comment by cardonator** [comment]
I am running this branch myself and I am not getting repeated messages from the docker logs.

Daemon mode is running great. I am having some config problems but I think they are my fault and not the container. Gotta keep tweaking dat config.

**Comment by cpoppema** [comment]
Thanks for letting me know it works for you fine too. I wonder if @konsumer still has problems or if I can merge this as-is.

**Comment by konsumer** [comment]
I will try it out today, but if it's working for you guys, maybe you could just merge, and I'll report if I find any issues.

**Comment by dewey** [comment]
@konsumer Have you tested it? Would be cool to have this in master :)

**Comment by cpoppema** [comment]
I'll agree with @konsumer's suggestion and leave this issue open but merge this in the meantime.

**Comment by konsumer** [comment]
Sorry, haven't had a chance to test this week, very busy. I will try to test soon.

**Comment by dewey** [comment]
@cpoppema small typo in the README I think, the run shouldn't be there right?

```
docker exec -it run flexget bash
```

**Comment by cpoppema** [comment]
Right :smile:

**Comment by dewey** [comment]
Just ran the latest version and everything including the daemon works flawlessly btw, thanks for the update!

**Comment by konsumer** [comment]
Works great with this config:

```yml
web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 1

tasks:
  task-a:
    rss: http://showrss.info/user/<MYSHOWRSSID>.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    all_series: yes
    transmission:
      host: <MYTRANSMISSIONIP>
      port: 9091
      path: /media/video/tv/{{series_name}}/Season {{series_season}}
      addpaused: no
```
