### ISSUE TITLE
Deluge plugin wont install. 

### ISSUE THREAD

**Issue by accessone67** [cpoppema/docker-flexget#32]
If running whit TORRENT_PLUGIN=deluge then it gives error:

> ERROR: unsatisfiable constraints:
  py-attrs (missing):
    required by: deluge-1.3.15-r2[py-attrs]
                 deluge-1.3.15-r2[py-attrs]
                 deluge-1.3.15-r2[py-attrs]
                 deluge-1.3.15-r2[py-attrs]
                 deluge-1.3.15-r2[py-attrs]
                 deluge-1.3.15-r2[py-attrs]

> 

and deluge part in config does not work

> DEBUG    task_queue                    task TASK-NAME aborted: TaskAbort(reason=Plugin `deluge` cannot be used because dependency `deluge` is missing., silent=False)
>

**Comment by cpoppema** [comment]
Hello @Tamps, thanks for your report.

It seems the deluge plugin received an update a couple of days ago and all I had to do was add a new dependency it now requires. If you run `docker pull cpoppema/docker-flexget` you should see an update.

You can reopen this issue if the problem remains :)

**Comment by jawilson** [comment]
@cpoppema Initially this worked fine, but I had blown away my docker image and ran again and I get:
```
flexget_1         | [cont-init.d] 22-update-deluge: executing...
flexget_1         | fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
flexget_1         | OK: 133 MiB in 73 packages
flexget_1         | fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
flexget_1         | ERROR: unsatisfiable constraints:
flexget_1         |   py-attrs-18.1.0-r0:
flexget_1         |     masked in: @edge
flexget_1         |     satisfies: world[py-attrs]
flexget_1         | fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
flexget_1         | fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
flexget_1         | ERROR: unsatisfiable constraints:
flexget_1         |   py-attrs-18.1.0-r0:
flexget_1         |     masked in: @edge
flexget_1         |     satisfies: deluge-1.3.15-r2[py-attrs]
```

I'm not very familiar with the alpine package manager so I can't quite figure out the issue here.

**Comment by cpoppema** [comment]
@jawilson If you run docker pull `cpoppema/docker-flexget` once more, you should see an update.

For some reason, the new dependency I added earlier (py-attrs package) was moved from the alpine repository edge/community to edge/main so the installer couldn't find it any more, hopefully it stays there. :)
