### ISSUE TITLE
 retry_failed plugin because waiting before retrying entry which has failed in the past

### ISSUE THREAD

**Issue by alebupal** [cpoppema/docker-flexget#37]
I have a nas with synology. I installed the docker and I have an error. I have tried several tracker and the same thing always happens.

`REJECTED: DC's Legends of Tomorrow S04E03 AMZN WEB DL 1080p AC3 5 1 Spanish English SUB by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: None)`

`web_server: yes
schedules:
  - tasks: *
    interval:
      minutes: 1
tasks:
  test:
    rss: url_rss
    series:
      - DC s Legends of Tomorrow
`

I do not know if this is a flexget or docker problem.
Greetings and thank you!

**Comment by cpoppema** [comment]
Hi @alebupal, I suggest you drop by the FlexGet forums first to see if they can help you since it looks like a generic problem. I would love to be of help, but since it says `failure reason: None` I can't say where to look.

I can only suggest to look for an earlier log message that can give a clue to what went wrong in the first place: the message you posted should only appear after it recently tried to download but failed and it attempt to retry that download too quickly.

**Comment by alebupal** [comment]
ok, I understand perfectly. Thank you very much for answering!
There is another thing that happens to me and that is that by putting the pss of the web service, it tells me.
I put the password variable
https://prnt.sc/lkvdeq
But when trying to enter the interface it always puts me the same
http://prntscr.com/lkvfjr
I have tried changing the password with:
`flexget web passwd <new_password>`
and it does not work.

**Comment by cpoppema** [comment]
If you tried to set it through executing the command suggested by the login screen: that won't work, see this example:

```
root@607d4d95ac0e:/$ flexget web passwd alebupal
2018-11-20 22:26 CRITICAL manager                       Failed to find configuration file config.yml
2018-11-20 22:26 INFO     manager                       Tried to read from: /, /root/.flexget, /root/.config/flexget
Could not instantiate manager: No configuration file found.
```

If you have mounted the host-directory to /config it will not automatically detect the configuration file. To workaround this issue you can the `-c` parameter:

```
root@607d4d95ac0e:/$ flexget -c /config/config.yml web passwd alebupal
There is a FlexGet process already running for this config, sending execution there.
Password 'alebupal' is not strong enough. Suggestions: Add another word or two. Uncommon words are better.
```

However, FlexGet uses a third-party piece of software to recognize a "strong" password and this fails this detection. FlexGet will refuse to set this password - if `WEB_PASSWD` would've worked, FlexGet still would've rejected that password.

I will also try to reproduce it for myself using `WEB_PASSWD` to see if it still works for me and perhaps try to detect if FlexGet rejected to password so anyone can update the password and try again.
