### ISSUE TITLE
Docker container fails on startup due to .config-lock

### ISSUE THREAD

**Issue by carlba** [cpoppema/docker-flexget#38]
What about adding 

```bash
# Make sure the .config-lock file is absent on start of Docker container
rm -rf /config/.config-lock
```
to 20-update-flexget.sh

**Comment by cpoppema** [comment]
Hi @carlba, sorry for this late reply.

The `.config-lock` is a file created by FlexGet and assumingly left behind if the process died for reason (or server power outage).

It is however also possible another instance of FlexGet is already running - assuming you see this error:

```Invalid lock file. Make sure FlexGet is not running, then delete it.```

While it is OK to remove it manually and restart FlexGet, this docker container does not have the access to check whether or not there might be another FlexGet (dockerized or not) currently using `.config-lock`.

I will think about supporting this behavior however, one way or another. Most likely with a default-enabled environment variable. Thanks for reporting :+1:

**Comment by cpoppema** [comment]
I'm just putting this here before I forget: Following FlexGet's own example in https://flexget.com/InstallWizard/SynologyNAS/Docker removing the lock file is not an issue whatsoever.

```
#!/bin/sh
if [ -f ~/.flexget/.config-lock ]; then
    rm ~/.flexget/.config-lock
fi
```

**Comment by Oshayr** [comment]
I like the idea of the environment variable for this.

**Comment by cpoppema** [comment]
Have you run into issues with this recently @Chaosmagnetx ? Just curious.

**Comment by cpoppema** [comment]
While working on a different issue I ran into this problem myself, resulting in a boot-loop where I'd get an error saying connection refused. So it's finally here :smile:.
