### ISSUE TITLE
Upgrade from python 2.7 to 3.x

### ISSUE THREAD

**Issue by gangefors** [cpoppema/docker-flexget#40]
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as Python 2.7 won't be maintained after that date.
A future version of pip will drop support for Python 2.7.
```

Since flexget [have support for Python 3](https://www.flexget.com/InstallWizard/Linux) this image should update before Python 2 reaches EOL.

**Comment by cpoppema** [comment]
Thanks for creating an issue for this.

I hope to look into this in the upcoming week. I've glanced at the python3 packages available in alpine. It seems that both alpine v3.7 and the newer v3.9 have python version 3.6.x which might need some testing/investigating.

If I can rely on CircleCI (which tests functionality for flexget automatically), it should work with both python versions 3.6 and 3.7, but the test coverage is "only" at 65%.

**Comment by cpoppema** [comment]
I tried switching base images to `lsiobase/alpine.python3:3.9`, but alpine doesn't have all packages using python 3. For example https://pkgs.alpinelinux.org/package/edge/testing/x86_64/libtorrent-rasterbar still depends on python2 and boost-python2. I will continue to look every once in a while if things have changed!

**Comment by cpoppema** [comment]
Hello @gangefors 

This month a python3-compatible package libtorrent-rasterbar was released for alpine that replaces the python2 package. This meant I could finally go ahead and make python3 the default. There is no way back now since the python2 package disappeared also.

If you pull the latest you'll get the image with python3! :)

**Comment by gangefors** [comment]
Thanks for your work.

I'll test this out when I have the time. Nice that another project has moved away from py2 :smiley:
