### ISSUE TITLE
dependency `libtorrent`

### ISSUE THREAD

**Issue by leeiberry** [cpoppema/docker-flexget#41]
TaskAbort(reason=Plugin `convert_magnet` cannot be used because dependency `libtorrent` is missing., silent=False)

i saw the previous issue related to this problem , my understand was this dependency was fix , or did i get that wrong 
I have completely reloaded the image  but still getting related error .
other related errors/warning :
2019-04-08 20:47 CRITICAL task          TVShows         libtorrent package required
2019-04-08 20:47 WARNING  task          TVShows         Aborting task (plugin: convert_magnet)

complete log attached

thanks in advanced 
LeeB

[flexget.csv.log](https://github.com/cpoppema/docker-flexget/files/3054326/flexget.csv.log)

 file attached

**Comment by leeiberry** [comment]
saw this 
https://discuss.flexget.com/t/solved-centos-7-convert-magnet-not-detecting-libtorrent/4008

**Comment by cpoppema** [comment]
Thanks for reporting this. I will take a look.

**Comment by cpoppema** [comment]
@leeiberry can you run `docker pull cpoppema/docker-flexget` and try again ?

**Comment by leeiberry** [comment]
Bedtime here ... Will try in 12 hours time

**Comment by leeiberry** [comment]
thanks that has fixed that issue ... 
i see you included transmission in the build now 

the only problem i have now , before i get my system working again is this 

Good Fight 3x03 The One where Diane Joins the Resistance 720p` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Magnet URL)

still get the same failure even after deleting the databases etc

**Comment by cpoppema** [comment]
Great to hear! FYI: support for Transmission has been in this container from the start :)

As far as I can tell, magnet links are supported when using one of: qbittorrent, utorrent, rtorrent, transmission or deluge or the torrent_match plugin. 

I believe that you should've seen a different error if the convert_magnet plugin failed to download a magnet. Do you have this problem still, even with other examples, or did the issue resolve itself/work with other downloads ?

**Comment by leeiberry** [comment]
...fixed ,   just added the conver_magnet plugin , which was previously erroring out because of libtorrent.
thanks for your help ...  GREAT CONTAINER :)

**Comment by FallingReign** [comment]
How exactly did you solve this issue? I am facing the same thing.

**Comment by cpoppema** [comment]
Hi @FallingReign. Thanks for reporting. I just checked and the problem did indeed resurface.

Last time I fixed it by pinning a package to a version that is specific to python 2. This time, I needed to do the same for another package.

**Comment by FallingReign** [comment]
Any guidance on how I might be able to workaround the error?

```
... libtorrent package required
... Aborting task (plugin: convert_magnet)
```

**Comment by cpoppema** [comment]
It should be fixed in the new latest I pushed yesterday. You can run `docker pull cpoppema/docker-flexget` and recreate/rebuild your container.
