### ISSUE TITLE
Can't install GCC

### ISSUE THREAD

**Issue by arifkin88** [cpoppema/docker-flexget#42]
Hi, I'm trying to install cloudscraper, however when I do (pip install cloudscraper) I get an error saying, 
"unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1"
I then tried to install gcc several different ways, but have had no luck.  I need cloudscraper to enable the cfscraper plugin to deal with cloudflare.  Any ideas?
Thanks!

**Comment by cpoppema** [comment]
Hello @arifkin88, thanks for asking.

To install cloudscraper there indeed seem to be other dependencies necessary than plain old gcc. Long story short: installing `g++` instead should take care of all dependencies you'd ever need besides also installing `python-dev` (needed to be able to create python-bindings for a C program - a dependency of cloudscraper, Brotli, is written in C).

Please run `docker pull cpoppema/docker-flexget`, recreate your container and try again.

**Comment by arifkin88** [comment]
Worked! Thanks so much for the update and the great docker!
