### ISSUE TITLE
py2-libtorrent-rasterbar fails to install

### ISSUE THREAD

**Issue by ajph** [cpoppema/docker-flexget#45]
py2-libtorrent-rasterbar fails to install when bringing up the container:

```
flexget_1                | ERROR: unsatisfiable constraints:
flexget_1                |   py2-libtorrent-rasterbar (missing):
flexget_1                |     required by: world[py2-libtorrent-rasterbar]
```

Which means `convert_magenet` cannot be used

```
get shows aborted: TaskAbort(reason=Plugin `convert_magnet` cannot be used because dependency `libtorrent` is missing., silent=False)
```

Thanks

**Comment by cpoppema** [comment]
Thank you @ajph for reporting this. It looks like py2-libtorrent-rasterbar vanished from the alpine package list and has been replaced by py3-libtorrent-rasterbar. I will have to see if I can get it fixed today.

**Comment by cpoppema** [comment]
Can you run `docker pull cpoppema/docker-flexget`, recreate your container and try again @ajph ? Please let me know if it works again.

**Comment by ajph** [comment]
Looks to be working, thanks @cpoppema

**Comment by cpoppema** [comment]
Great to hear! :)
