### ISSUE TITLE
access to docker host

### ISSUE THREAD

**Issue by Anian-igor** [cpoppema/docker-flexget#47]
Hello.
First, at all thank you for your flexget docker image.
I'm using this image with deluge that required connection to docker host.
Do you have any possibilities to add a location to docker host IP?
For example: /sbin/ip -4 route list match 0/0 | /usr/bin/awk '{print $3" docker-host"}' >> /etc/hosts
Thank you.

**Comment by cpoppema** [comment]
Hi @Anian-igor, just to get a better understanding I have a couple questions.

If you run both flexget and deluge inside docker containers I would think you'd need to set ip address of the container that is running deluge in flexget's configuration. That is why I think I'm don't completely understand your question.

What /etc/hosts do you want to modify, the one inside a docker container ? The one with flexget or perhaps deluge ? Or /etc/hosts on your host system ?

One way to get the IP address from a docker container on your host is:

```
$ docker inspect --format '{{ .NetworkSettings.IPAddress }}' flexget
172.17.0.5
```
or
```
$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' flexget
172.17.0.5
```
Replace `flexget` with the container id or name that you have given your container.

Which one works for you can depend on your docker version.

If you always run a deluge and flexget container together you can also link these containers. Using a docker-compose.yml configuration for this makes it particularly easy but you can also do it without. Why would you want to do this ? With this you, docker automatically does /etc/hosts file thing for you inside the containers so they can access each other with just their names. (in the past this is exactly what happened, these days docker actually uses DNS to achieve the same thing).

If this is going in the wrong direction, I apologize in advance, please help me better understand your question :smile:

**Comment by Anian-igor** [comment]
I just start to use docker image. And just tried to add command that I found there https://github.com/docker/for-linux/issues/264#issuecomment-385698947
But with no luck. Docker container restarted all time.
I tried to do this because want to use static address in flexget to connect deluge like below
  deluge_local:
    deluge:
      host: host.docker.internal
      port: 58846
      username: user
      password: pass

**Comment by Anian-igor** [comment]
Deluge require "network_mode: host" to start so I cannot connect via container name inside docker-compose file
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host

**Comment by cpoppema** [comment]
I'm not sure you can achieve what you want with `host.docker.internal`. It seems like it only gives you the ip address of your docker gateway (if it would actually be working on linux), or is that gateway supposed to redirect traffic on a known container port to the host network as well ?

Something you can try if your host system has a static ip: use that ip address in the flexget configuration. I do the same for my own transmission container. This container runs without the host network mode but I don't believe that would matter.

```
    transmission:
        host: 192.168.1.111
        port: 9091
```

**Comment by Anian-igor** [comment]
Oh. Really. My host's IP availible from docker container. This very helpfull.
Yes. I tried access docker gateway there deluge was run.
Very thanks.
