### ISSUE TITLE
irc_bot package not installed

### ISSUE THREAD

**Issue by wbern** [cpoppema/docker-flexget#49]
I had to modify to this since I wanted to use the irc daemon.
```
    && pip3 install --no-cache-dir paver irc_bot transmissionrpc \
```

Also I had to install bash which I kind of needed for some side scripts that I've been keeping with flexget long before docker. Maybe that could be considered for people who like to extend flexget with bash scripts.. I don't know.

**Comment by cpoppema** [comment]
Hello again. You are right that bash is not available in the conventional way by just calling `bash`. In this image, since it uses something called s6 overlay, you can run bash scripts with this shebang:

```
#!/usr/bin/with-contenv bash
```

I hope that helps.

I will have to verify if irc bot is working on not later. How did you determine it is missing?

**Comment by cpoppema** [comment]
When starting flexget and running python inside the container it looks like irc_bot should be working just fine:

```
$ docker exec -it flexget bash
root@124a9060976c:/# python3
Python 3.7.3 (default, Apr 17 2019, 11:48:37) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from irc_bot import utils as irc_bot
>>> 
```

If it wasn't, I had expected to see:
```
ImportError: No module named irc_bot
```

Is paver a dependency you needed maybe ?

**Comment by wbern** [comment]
Try running flexget daemon start

**Comment by cpoppema** [comment]
Yes, flexget daemon start is what is started automatically when starting a container. With a config.yml containing only (part of) example configuration as shown on https://flexget.com/Plugins/Daemon/irc, I see the following in my docker logs:

```
2019-07-31 18:24 INFO     irc     Starting IRC connection for irc_cool_tracker
2019-07-31 18:24 INFO     irc     Tracker file not found on disk. Attempting to fetch tracker config file from Github.
```

To me that looks like Flexget can utilize the irc_bot package at least. What do you see ?

**Comment by cpoppema** [comment]
Does this still doesn't work for you @wbern ? If it does I'd like to have this ticket closed :smile:.

**Comment by wbern** [comment]
Unfortunately can't test now, but if you can't reproduce I would close it!

**Comment by cpoppema** [comment]
Thanks. Feel free to reopen if you have more information available :+1:.
