### ISSUE TITLE
Default config.yml is missing - flexget does not start at all

### ISSUE THREAD

**Issue by kolayuk** [cpoppema/docker-flexget#6]
It'll be better if you'll include some basic config.yml, because of now flexget does not start at all, it pushes error to log "config/config.yml is missing"

**Comment by cpoppema** [comment]
Hi @kolayuk, thank you for the suggestion. I expect this to be difficult since everybody uses flexget differently, but I will investigate if a valid config can be created without too many working tasks in it.
Did you manage to take a look at the link to an example config at the top of the README?

**Comment by kolayuk** [comment]
Sure, I used tutorial and all works fine now. But you should add to readme a line about config.yml is REQUIRED! My expectations was it should create with first run...

**Comment by JoeStratton** [comment]
This default example file will work if you want to add it to the image:

web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes

tasks:
 task name:
    rss: http://example.com/torrents.xml
    series:
      - pioneer one
      - some series
    download: /config

**Comment by cpoppema** [comment]
I've finally come around and added a sample config.yml to the README :)
