### ISSUE TITLE
add additional Python Packages

### ISSUE THREAD

**Issue by antibios** [cpoppema/docker-flexget#60]
Hi,
  Can we provide a list of python packages in addition to load via pip during start up?  Some flexget packages require additional python modules like:
https://flexget.com/Plugins/Notifiers/xmpp
pip install sleekxmpp

Thanks

**Comment by cpoppema** [comment]
Hello @antibios I have just pushed an update that includes sleekxmpp so there is no need to manually install it during startup. However, I acknowledge it can be a pain to wait for an image update and not everyone has the possibility to install packages through `docker exec` to get what they want. For this reason I have also included in this update, a way to modify what packages are installed (additionally) using a requirements.txt. Check out the README :smile:. If you have any questions or run into any issues, let me know!

If you miss any packages in the future, please come back and create an issue for it as well so I can include it in the image.
