### ISSUE TITLE
Startup error: Compile failed: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by aazimh** [cpoppema/docker-flexget#63]
Hi - I've had this container installed on my Ubuntu machine for a month or so now, but just recently noticed it stopped and now fails to run. I tried to re-pull it, but get the following error when it starts up and tries to install dependencies:

[Pastebin link since the indentation wasn't working.](https://pastebin.com/0XztVwrw)

Not really sure how to get around this (fairly new to the world of Docker) but would appreciate any help - thanks!

**Comment by dangmai** [comment]
Same for me, it stopped working for 3.1.1, because of new dependencies (lxml is the culprit here).

**Comment by cpoppema** [comment]
Thanks for the log :) While py3-lxml (and libxml2) are already installed, libxml2-dev/libxslt-dev are now also needed. I will add these to the system packages and have to confirm this works before uploading new images, but it can take a while as I'm on the go right now.

Right after you start your container you might just have enough time to run this yourself in the meantime:

```
docker exec flexget apk update
docker exec flexget apk add libxml2-dev libxslt-dev
```

If you're lucky flexget can be updated in the same run or after another restart of the container.

**Comment by cpoppema** [comment]
New builds are finally up! If you haven't tried the workaround or if it didn't work you, can pull the new image with `docker pull cpoppema/docker-flexget`.

**Comment by aazimh** [comment]
@cpoppema Works great, thanks so much for the quick action on this! Really appreciate it.
