### ISSUE TITLE
Add config editor back to Web UI?

### ISSUE THREAD

**Issue by arifkin88** [cpoppema/docker-flexget#64]
I used to edit my config file in the web UI, but when I just updated it seems like that option is no longer there.  Is it possible to bring back?

**Comment by cpoppema** [comment]
Hello @arifkin88. FlexGet has started working on replacing their webui and it looks like it's not a complete replacement yet, so there are menu items missing that you could use before. To get the old webui back for now, you can edit your config.yml by adding `run_v1: yes` under `web_server`.

```
web_server:
  run_v1: yes
```

Don't worry if you're still not seeing a config editor, this setting means that both the new webui and old webui are running alongside each other. To see the old editor, open the webui, edit the address bar in your browser and add `v1/` after the port number, ie. `http://localhost:5050/#/` becomes `http://localhost:5050/v1/#/`. You can also visit to `http://localhost:5050/v1/` directly.

**Comment by arifkin88** [comment]
That worked! Thanks so much @cpoppema !
