### ISSUE TITLE
port 5050

### ISSUE THREAD

**Issue by marine1988** [cpoppema/docker-flexget#69]
Why you use port 5050  instead of default 3539? Can I use default port?

**Comment by cpoppema** [comment]
Hello @marine1988.

You can use any port you want. Simply replace the number 5050 with 3539 where necessary in

```
-p 5050:5050 \
```
for the docker example or

```
    ports:
      - 5050:5050
```
for the docker-compose example.
Left is the port number that is used in the URL you  go to, the right port number is the port number in config.yml.

As far as I can tell, 5050 *is* the default port, meaning if you do not add 

```
web_server:
  bind: 0.0.0.0
  port: 3539
```

or simply

```
web_server: 3539
```
to config.yml, the port is actually 5050. The only mention of 3539 is on the page https://flexget.com/Web-UI as part of an example on how to configure a _custom_ port.

I hope this clears things up :slightly_smiling_face:
