### ISSUE TITLE
Pin pip package to get around bug in pip

### ISSUE THREAD

**Issue by cardonator** [cpoppema/docker-flexget#7]
As discussed here https://github.com/pypa/setuptools/issues/951 there is currently a bug in pip that causes problems when replacing existing packages. This container is currently experiencing that on pyparsing.

Can you pin pip to an earlier version so this will stop happening? :)

**Comment by cpoppema** [comment]
Thanks for pointing this out @cardonator, I have, as I have seen others do, as a response to the mentioned issue, pinned a package `setuptools` to version 32.

**Comment by cardonator** [comment]
Thanks, sir!
