### ISSUE TITLE
Flexget not starting

### ISSUE THREAD

**Issue by AdamsLab01** [cpoppema/docker-flexget#79]
Flexget had been running fine on this system before updating it via apt. After a reboot I found that Flexget was not starting, stays in a loop. I can't make heads or tails of the logs but it looks like the main issue is causing this error to be logged 

"AttributeError: module 'pytz' has no attribute 'BaseTzInfo'"

I've removed and reinstalled the container but no luck getting Flexget to start.

Attatched is a log starting from a fresh install.

[FlexgetLog.txt](https://github.com/cpoppema/docker-flexget/files/5446400/FlexgetLog.txt)

**Comment by cpoppema** [comment]
This sounds exactly like the issue reported in https://github.com/cpoppema/docker-flexget/issues/77. Good news, you should be good to go if you pull the latest version of the image, to read how, see [here](https://github.com/cpoppema/docker-flexget/issues/77#issuecomment-709473337).

**Comment by AdamsLab01** [comment]
Latest version solves the issue. THANK YOU!
