### ISSUE TITLE
Supposedly Setuptools has fixed their vendoring problem

### ISSUE THREAD

**Issue by cardonator** [cpoppema/docker-flexget#8]
In #7, setuptools was pinned to v33 to prevent weird problems with updating in the Docker setup.

https://github.com/pypa/setuptools/issues/951 has now been closed and setuptools v36 should work properly now. It might be worth checking and removing the package version pin that was added.

**Comment by cpoppema** [comment]
Thank you for following up on this! I will look into it and change the pin to >= 36 if it works 👍.
