### ISSUE TITLE
AttributeError: module 'pytz' has no attribute 'BaseTzInfo'

### ISSUE THREAD

**Issue by duartejbrito** [cpoppema/docker-flexget#80]
Running a new container and doing `flexget check` give me that result:

![image](https://user-images.githubusercontent.com/7522311/98269136-4e516280-1f85-11eb-8fb0-961c6ed4d73d.png)
![image](https://user-images.githubusercontent.com/7522311/98269340-7fca2e00-1f85-11eb-9357-937b5c0d7cfe.png)

Accessing the container using `docker exec -it flexget bash` and run `pip install -U pytz` solve the issue.

We need to add `pytz` to `requirements.txt` file.

**Comment by duartejbrito** [comment]
Some more info: https://github.com/Flexget/Flexget/issues/2749

**Comment by cpoppema** [comment]
Hello @duartejbrito. This sounds exactly like the issue reported in https://github.com/cpoppema/docker-flexget/issues/77. Good news, you should be good to go if you pull the latest version of the image, to read how, see [here](https://github.com/cpoppema/docker-flexget/issues/77#issuecomment-709473337).

Adding pytz to the requirements overrides the version installed that is pinned by Flexget, which ideally shouldn't be necessary.  https://github.com/cpoppema/docker-flexget/pull/76 fixed it instead by not upgrading to the latest telegram-bot plugin.

**Comment by duartejbrito** [comment]
Hi @cpoppema. When I created the issue, I recreated a new container with an old version of the image, and I didn't notice that.
Now I recreated again but forcing the new version, and all good.
Thanks for the help!!!
