### ISSUE TITLE
CRITICAL Error: transmission-rpc module version 0.11 or higher required

### ISSUE THREAD

**Issue by antonfischl1980** [cpoppema/docker-flexget#84]
Hi,

it seems upstream flexget switch from "transmissionrpc" to "transmission-rpc" module. See [this pull request on flexget](https://github.com/Flexget/Flexget/pull/2791)

**Comment by carlba** [comment]
Adding this to 21-update-transmission should fix it.

```bash
#!/usr/bin/with-contenv bash

if [ -z "$TORRENT_PLUGIN" ] || [[ "$TORRENT_PLUGIN" == *"transmission"* ]]; then
    pip uninstall -U transmissionrpc
    pip install -U transmission-rpc    
fi
```

**Comment by cpoppema** [comment]
Thanks for bringing this to my attention. To change packages before new images are available you can run

```
docker exec flexget pip install -U transmission-rpc
```

I am working on building and publishing new images as soon as I can.

**Comment by antonfischl1980** [comment]
I did the "docker exec flexget pip install -U transmission-rpc"

Now I'm getting this error:

BUG: Unhandled error in plugin from_transmission: name 'TransmissionError' is not defined

**Comment by carlba** [comment]
Thanks for the rapid fix!

**Comment by carlba** [comment]
Why is it not propagated to dockerhub though?

**Comment by cpoppema** [comment]
> Why is it not propagated to dockerhub though?

That's because I'm building multi-arch locally and that takes a few hours with building libtorrent-rasterbar. New images are available now. :)

**Comment by cpoppema** [comment]
> I did the "docker exec flexget pip install -U transmission-rpc"
> 
> Now I'm getting this error:
> 
> BUG: Unhandled error in plugin from_transmission: name 'TransmissionError' is not defined

I'm sorry this shortcut did not work for you. Please pull the new image and recreate the container :)
