### ISSUE TITLE
transmission-rpc module version 3.0 or higher required

### ISSUE THREAD

**Issue by AdamsLab01** [cpoppema/docker-flexget#86]
Not sure if this is a flexget issue or a Transmission issue but just noticed this started happening, flexget does not seem to be able to connect to transmission. Note that I'm using the LinuxServer.io transmission container.

**Comment by AdamsLab01** [comment]
Note, I don't have authentication or white/black listing enabled.

**Comment by AdamsLab01** [comment]
FYI removed the existing container and pulled the latest image (docker pull cpoppema/docker-flexget) and rebuilt the container. All seems to be working now.

**Comment by cpoppema** [comment]
Great to hear the latest version solved this for you :)
