### ISSUE TITLE
Nginx Reverse-Proxy for Flexget

### ISSUE THREAD

**Issue by XxAcielxX** [cpoppema/docker-flexget#87]
Hello there,

I'm trying to setup reverse-proxy for this container, but I'm unable to make it. I want the subfolder style config for my setup.

I have linuxserver/swag running with my other services but only this one service (your Flexget container) is remaining.

**flexget.subfolder.conf**
```
location /flexget {
    return 301 $scheme://$host/flexget/;
}

    location ^~ /flexget/ {

        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app flexget;
        set $upstream_port 5050;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        
        rewrite /flexget(.*) $1 break;
        
    }
```

When I visit https://my-domain.com/flexget, all I get is an empty page with the page title saying **Flexget Manager**.

Do I need any additional settings for this to work out? Kindly help.

**Regards~**

**Comment by cpoppema** [comment]
Hello @XxAcielxX. My guess is that you're missing `/flexget` as a base_url in your flexget config.yml, can you try that out ? 

https://flexget.com/Web-UI
> base_url: Set a different base_url; default is /

**Comment by XxAcielxX** [comment]
> Hello @XxAcielxX. My guess is that you're missing `/flexget` as a base_url in your flexget config.yml, can you try that out ?
> 
> https://flexget.com/Web-UI
> 
> > base_url: Set a different base_url; default is /

At the top of my config.yml it reads now:

```
web_server: yes
base_url: /flexget

schedules:
  - tasks: '*'
    interval:
      minutes: 10

... 
```

It is showing this error in the container log:

```

Could not start manager: Did not pass schema validation.


2021-02-22 12:51:48 ERROR    stevedore.extension                 Could not load 'addic7ed': unexpected indent (addic7ed.py, line 234)


2021-02-22 12:51:51 CRITICAL manager                       [/] The key `base_url` is not valid here.


2021-02-22 12:51:51 CRITICAL manager                       Failed to load config file: Did not pass schema validation.


Could not start manager: Did not pass schema validation.


2021-02-22 12:51:55 ERROR    stevedore.extension                 Could not load 'addic7ed': unexpected indent (addic7ed.py, line 234)
```
Web Server doesn't load at all like this.

**Comment by cpoppema** [comment]
The top-level configuration for `web_server` only supports yes/no or a port number from what I read on https://flexget.com/Web-UI. To configure the base_url you need to indent it like shown in the "Fully configured example".

```
web_server:
  web_ui: yes
  base_url: /flexget
```

**Comment by XxAcielxX** [comment]
Did the above the edits, it's working with a slight change just for the info.

Reverse-Proxy URL: https://my-domain.com/flexget
Local Network: lan-ip:5050/flexget (not lan-ip:5050)
