### ISSUE TITLE
WEB_PASSWD Environment Variable?

### ISSUE THREAD

**Issue by JoeStratton** [cpoppema/docker-flexget#9]
Hi! I love this image due to the auto updating, but I have also seen some flexget images with a variable to set the web password.

It can be troublesome to reset the password every time the container is restarted. Could this be added? Thanks!

**Comment by cpoppema** [comment]
Thanks for the renewed interest for this @JoeStratton. Pull request #4 went stale, but I'm sure I can make something work.

**Comment by JoeStratton** [comment]
Awesome! It is working in this image if you want an example:
https://github.com/activ/arch-flexget

That one just doesnt auto update

**Comment by cpoppema** [comment]
I've put something together! Let me know if you have any issues with it. For the commit, see https://github.com/cpoppema/docker-flexget/commit/5f5811ceba061ed616a4e42d120d54b4b2c26901.

**Comment by JoeStratton** [comment]
working great!
